/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Interview Preparation",
  "tagline": "Interview Preparation for Computer Science Interviews",
  "url": "https://shyamzzp.github.io/interview",
  "baseUrl": "/interview/",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "favicon": "img/favicon.ico",
  "organizationName": "shyamzzp",
  "projectName": "interview",
  "deploymentBranch": "main",
  "trailingSlash": false,
  "themes": [
    "@docusaurus/theme-live-codeblock"
  ],
  "titleDelimiter": "•",
  "scripts": [
    "https://kit.fontawesome.com/307bcbc229.js",
    "https://unpkg.com/driver.js/dist/driver.min.js",
    "https://unpkg.com/driver.js/dist/driver.min.css",
    "/static/scrolltotop.js"
  ],
  "plugins": [
    [
      "@docusaurus/plugin-pwa",
      {
        "debug": true,
        "offlineModeActivationStrategies": [
          "appInstalled",
          "standalone",
          "queryString"
        ],
        "pwaHead": [
          {
            "tagName": "link",
            "rel": "manifest",
            "href": "/manifest.json"
          },
          {
            "tagName": "meta",
            "name": "theme-color",
            "content": "#1877F2"
          }
        ]
      }
    ]
  ],
  "presets": [
    [
      "@docusaurus/preset-classic",
      {
        "docs": {
          "sidebarPath": "C:\\Users\\shyam\\Desktop\\Self Projects\\interview\\sidebars.js"
        },
        "blog": {
          "blogTitle": "Comp Labs Blog",
          "blogSidebarTitle": "All Posts",
          "blogSidebarCount": "ALL",
          "sortPosts": "ascending",
          "feedOptions": {
            "type": "all",
            "copyright": "Copyright © 2022 Comp Labs. All Rights Reserved."
          }
        },
        "theme": {
          "customCss": "C:\\Users\\shyam\\Desktop\\Self Projects\\interview\\src\\css\\custom.css"
        },
        "sitemap": {
          "changefreq": "always",
          "priority": 1
        },
        "gtag": {
          "trackingID": "UA-203163469-1",
          "anonymizeIP": true
        }
      }
    ]
  ],
  "themeConfig": {
    "liveCodeBlock": {
      "playgroundPosition": "bottom"
    },
    "metadata": [
      {
        "name": "theme-color",
        "content": "#1877F2"
      }
    ],
    "docs": {
      "sidebar": {
        "hideable": true,
        "autoCollapseCategories": true
      },
      "versionPersistence": "localStorage"
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": true
    },
    "prism": {
      "theme": {
        "plain": {
          "backgroundColor": "#282c34",
          "color": "#ffffff"
        },
        "styles": [
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "#c5a5c5"
            }
          },
          {
            "types": [
              "attr-value"
            ],
            "style": {
              "color": "#8dc891"
            }
          },
          {
            "types": [
              "comment",
              "block-comment",
              "prolog",
              "doctype",
              "cdata",
              "shebang"
            ],
            "style": {
              "color": "#999999"
            }
          },
          {
            "types": [
              "property",
              "number",
              "function-name",
              "constant",
              "symbol",
              "deleted"
            ],
            "style": {
              "color": "#5a9bcf"
            }
          },
          {
            "types": [
              "boolean"
            ],
            "style": {
              "color": "#ff8b50"
            }
          },
          {
            "types": [
              "tag"
            ],
            "style": {
              "color": "#fc929e"
            }
          },
          {
            "types": [
              "string"
            ],
            "style": {
              "color": "#8dc891"
            }
          },
          {
            "types": [
              "punctuation"
            ],
            "style": {
              "color": "#8dc891"
            }
          },
          {
            "types": [
              "selector",
              "char",
              "builtin",
              "inserted"
            ],
            "style": {
              "color": "#D8DEE9"
            }
          },
          {
            "types": [
              "function"
            ],
            "style": {
              "color": "#79b6f2"
            }
          },
          {
            "types": [
              "operator",
              "entity",
              "url",
              "variable"
            ],
            "style": {
              "color": "#d7deea"
            }
          },
          {
            "types": [
              "keyword"
            ],
            "style": {
              "color": "#c5a5c5"
            }
          },
          {
            "types": [
              "at-rule",
              "class-name"
            ],
            "style": {
              "color": "#FAC863"
            }
          },
          {
            "types": [
              "important"
            ],
            "style": {
              "fontWeight": "400"
            }
          },
          {
            "types": [
              "bold"
            ],
            "style": {
              "fontWeight": "bold"
            }
          },
          {
            "types": [
              "italic"
            ],
            "style": {
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "backgroundColor": "#282c34",
          "color": "#ffffff"
        },
        "styles": [
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "#c5a5c5"
            }
          },
          {
            "types": [
              "attr-value"
            ],
            "style": {
              "color": "#8dc891"
            }
          },
          {
            "types": [
              "comment",
              "block-comment",
              "prolog",
              "doctype",
              "cdata",
              "shebang"
            ],
            "style": {
              "color": "#999999"
            }
          },
          {
            "types": [
              "property",
              "number",
              "function-name",
              "constant",
              "symbol",
              "deleted"
            ],
            "style": {
              "color": "#5a9bcf"
            }
          },
          {
            "types": [
              "boolean"
            ],
            "style": {
              "color": "#ff8b50"
            }
          },
          {
            "types": [
              "tag"
            ],
            "style": {
              "color": "#fc929e"
            }
          },
          {
            "types": [
              "string"
            ],
            "style": {
              "color": "#8dc891"
            }
          },
          {
            "types": [
              "punctuation"
            ],
            "style": {
              "color": "#8dc891"
            }
          },
          {
            "types": [
              "selector",
              "char",
              "builtin",
              "inserted"
            ],
            "style": {
              "color": "#D8DEE9"
            }
          },
          {
            "types": [
              "function"
            ],
            "style": {
              "color": "#79b6f2"
            }
          },
          {
            "types": [
              "operator",
              "entity",
              "url",
              "variable"
            ],
            "style": {
              "color": "#d7deea"
            }
          },
          {
            "types": [
              "keyword"
            ],
            "style": {
              "color": "#c5a5c5"
            }
          },
          {
            "types": [
              "at-rule",
              "class-name"
            ],
            "style": {
              "color": "#FAC863"
            }
          },
          {
            "types": [
              "important"
            ],
            "style": {
              "fontWeight": "400"
            }
          },
          {
            "types": [
              "bold"
            ],
            "style": {
              "fontWeight": "bold"
            }
          },
          {
            "types": [
              "italic"
            ],
            "style": {
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          }
        ]
      },
      "additionalLanguages": [
        "java"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "image": "img/shyamzzp-logo.png",
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 6
    },
    "navbar": {
      "hideOnScroll": true,
      "title": "📖 Inteview Preparation",
      "items": [
        {
          "to": "/docs/design-patterns/",
          "label": "Design Patterns 🚧",
          "position": "left"
        },
        {
          "type": "localeDropdown",
          "position": "right",
          "dropdownItemsBefore": [],
          "dropdownItemsAfter": []
        },
        {
          "href": "https://github.com/shyamzzp/interview",
          "position": "right",
          "className": "header-github-link",
          "aria-label": "GitHub Repository"
        },
        {
          "type": "dropdown",
          "label": "Data Structures",
          "position": "left",
          "items": [
            {
              "label": "Arrays",
              "to": "/docs/data-structures/arrays"
            },
            {
              "label": "Bit Manipulation",
              "to": "/docs/data-structures/bit-manipulation"
            },
            {
              "label": "Comparators",
              "to": "/docs/data-structures/comparators"
            },
            {
              "label": "Complexity",
              "to": "/docs/data-structures/complexity"
            },
            {
              "label": "Deque",
              "to": "/docs/data-structures/dequeue"
            },
            {
              "label": "DFS",
              "to": "/docs/data-structures/dfs"
            },
            {
              "label": "Graph",
              "to": "/docs/data-structures/graph"
            },
            {
              "label": "Linked List",
              "to": "/docs/data-structures/linked-list"
            },
            {
              "label": "Map",
              "to": "/docs/data-structures/map"
            },
            {
              "label": "Matrix",
              "to": "/docs/data-structures/matrix"
            },
            {
              "label": "Math",
              "to": "/docs/data-structures/math"
            },
            {
              "label": "Priority Queue",
              "to": "/docs/data-structures/priority-queue"
            },
            {
              "label": "Snippets",
              "to": "/docs/data-structures/snippets"
            },
            {
              "label": "Tree",
              "to": "/docs/data-structures/tree"
            },
            {
              "label": "Trie",
              "to": "/docs/data-structures/trie"
            }
          ]
        },
        {
          "type": "dropdown",
          "label": "Algorithms",
          "position": "left",
          "items": [
            {
              "label": "Common Algorithms",
              "to": "/docs/data-structures/algorithms"
            },
            {
              "label": "Common Problems",
              "to": "/docs/data-structures/common-problems"
            },
            {
              "label": "Search Algorithms",
              "to": "/docs/data-structures/search-algorithms"
            },
            {
              "label": "Sorting Algorithms",
              "to": "/docs/data-structures/sorting-algorithms"
            }
          ]
        },
        {
          "type": "dropdown",
          "label": "System Design",
          "position": "left",
          "items": [
            {
              "label": "Instagram System Design",
              "to": "/interview/docs/system-design/instagram"
            },
            {
              "label": "Netflix System Design",
              "to": "/interview/docs/system-design/netflix"
            },
            {
              "label": "Pastebin System Design",
              "to": "/interview/docs/system-design/pastebin"
            },
            {
              "label": "Tinyurl System Design",
              "to": "/interview/docs/system-design/tinyurl"
            },
            {
              "label": "Top 10 System Design Overview",
              "to": "/interview/docs/system-design/top-10-system-design"
            },
            {
              "label": "Twitter System Design",
              "to": "/interview/docs/system-design/twitter-system-design"
            },
            {
              "label": "Uber/Lyft System Design",
              "to": "/interview/docs/system-design/uber"
            }
          ]
        },
        {
          "type": "dropdown",
          "label": "Glossary",
          "position": "left",
          "items": [
            {
              "label": "Data Structures Glossary",
              "to": "/interview/docs/data-structures/ds-glossary"
            },
            {
              "label": "System Design Glossary",
              "to": "/interview/docs/system-design/glossary"
            }
          ]
        }
      ]
    }
  },
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "stylesheets": [],
  "clientModules": [],
  "noIndex": false
};
