export default {
  '17896441': [() => import(/* webpackChunkName: '17896441' */ '@theme/DocItem'), '@theme/DocItem', require.resolveWeak('@theme/DocItem')],
  '1be78505': [() => import(/* webpackChunkName: '1be78505' */ '@theme/DocPage'), '@theme/DocPage', require.resolveWeak('@theme/DocPage')],
  '3d941b31': [() => import(/* webpackChunkName: '3d941b31' */ '@site/docs/design-patterns/design-patterns.md'), '@site/docs/design-patterns/design-patterns.md', require.resolveWeak('@site/docs/design-patterns/design-patterns.md')],
  '5e9f5e1a': [() => import(/* webpackChunkName: '5e9f5e1a' */ '@generated/docusaurus.config'), '@generated/docusaurus.config', require.resolveWeak('@generated/docusaurus.config')],
  '935f2afb': [() => import(/* webpackChunkName: '935f2afb' */ '~docs/default/version-current-metadata-prop-751.json'), '~docs/default/version-current-metadata-prop-751.json', require.resolveWeak('~docs/default/version-current-metadata-prop-751.json')],
  '9dd8a0d2': [() => import(/* webpackChunkName: '9dd8a0d2' */ '@site/src/pages/index.jsx'), '@site/src/pages/index.jsx', require.resolveWeak('@site/src/pages/index.jsx')],
  '9e28065d': [() => import(/* webpackChunkName: '9e28065d' */ 'C:\\Users\\shyam\\Desktop\\comp-labs-website-main\\comp-labs-website-main\\.docusaurus\\docusaurus-plugin-content-pages\\default\\plugin-route-context-module-100.json'), 'C:\\Users\\shyam\\Desktop\\comp-labs-website-main\\comp-labs-website-main\\.docusaurus\\docusaurus-plugin-content-pages\\default\\plugin-route-context-module-100.json', require.resolveWeak('C:\\Users\\shyam\\Desktop\\comp-labs-website-main\\comp-labs-website-main\\.docusaurus\\docusaurus-plugin-content-pages\\default\\plugin-route-context-module-100.json')],
  'dc42a44a': [() => import(/* webpackChunkName: 'dc42a44a' */ 'C:\\Users\\shyam\\Desktop\\comp-labs-website-main\\comp-labs-website-main\\.docusaurus\\docusaurus-plugin-content-docs\\default\\plugin-route-context-module-100.json'), 'C:\\Users\\shyam\\Desktop\\comp-labs-website-main\\comp-labs-website-main\\.docusaurus\\docusaurus-plugin-content-docs\\default\\plugin-route-context-module-100.json', require.resolveWeak('C:\\Users\\shyam\\Desktop\\comp-labs-website-main\\comp-labs-website-main\\.docusaurus\\docusaurus-plugin-content-docs\\default\\plugin-route-context-module-100.json')],};
